---

- name: Install ssl-cert package
  become: true
  apt:
    pkg:
      - ssl-cert
    update_cache: true
    cache_valid_time: 60
    state: "{{ greenlight_state }}"

- import_tasks: certificate-letsencrypt.yml
  when: greenlight_letsencrypt_enable|bool

- import_tasks: certificate-custom.yml
  when: greenlight_own_cert is defined

- name: Ensure greenlight_ssl_cert exists
  become: true
  file:
    path: "{{ greenlight_ssl_cert }}"

- name: Ensure proper file permissions on greenlight_ssl_key
  become: true
  file:
    path: "{{ greenlight_ssl_key }}"
    owner: "root"
    group: "{{'ssl-cert' if ansible_os_family == 'Debian' else 'root' }}"
    mode: '0440'
